-- Release pins. Plugins omitted here either do not cut useful releases or are
-- intentionally tracking a maintained branch in lazy-lock.json.
return {
  { "L3MON4D3/LuaSnip", tag = "v2.5.0" },
  { "MeanderingProgrammer/render-markdown.nvim", tag = "v8.12.0" },
  { "MunifTanjim/nui.nvim", branch = "main" },
  { "folke/flash.nvim", tag = "v2.1.0" },
  { "folke/lazydev.nvim", tag = "v1.10.0" },
  { "folke/noice.nvim", tag = "v4.10.0" },
  { "folke/todo-comments.nvim", tag = "v1.5.0" },
  { "folke/trouble.nvim", tag = "v3.7.1" },
  { "folke/which-key.nvim", tag = "v3.17.0" },
  { "fredrikaverpil/neotest-golang", tag = "v2.9.0" },
  { "jay-babu/mason-nvim-dap.nvim", tag = "v2.5.2" },
  { "kevinhwang91/nvim-bqf", tag = "v1.1.1" },
  { "kylechui/nvim-surround", tag = "v4.0.5" },
  { "lambdalisue/vim-suda", tag = "v1.2.4" },
  { "lewis6991/gitsigns.nvim", tag = "v2.1.0" },
  { "lukas-reineke/indent-blankline.nvim", tag = "v3.9.1" },
  { "mfussenegger/nvim-dap", tag = "0.10.0" },
  { "mrcjkb/rustaceanvim", tag = "v9.0.4" },
  { "nvim-neotest/neotest", tag = "v5.18.0" },
  { "nvim-neotest/nvim-nio", tag = "v1.10.1" },
  { "nvim-telescope/telescope.nvim", tag = "v0.2.2" },
  { "rcarriga/nvim-dap-ui", tag = "v4.0.0" },
  { "rcarriga/nvim-notify", tag = "v3.15.0" },
  { "stevearc/aerial.nvim", tag = "v4.0.0" },
  { "stevearc/conform.nvim", tag = "v9.1.0" },
  { "stevearc/dressing.nvim", tag = "v3.1.1" },
  { "stevearc/oil.nvim", tag = "v2.16.0" },
  { "williamboman/mason-lspconfig.nvim", tag = "v2.2.0" },
  { "williamboman/mason.nvim", tag = "v2.3.0" },
  { "echasnovski/mini.nvim", tag = "v0.17.0" },
  { "echasnovski/mini.icons", tag = "v0.17.0" },
}
